2023-07-06 19:28:50,557 ERROR handle_logs type: invalid literal for int() with base 10: '' -> traceback:"    (<frame at 0x0000022DEA3765C0, file 'C:\\Users\\BURI\\Desktop\\add_all_extra\\python\\BuriScript - A Code Editor\\TypeRacer\\buriracer_timer.py', line 32, code <lambda>>, 40, 32, <traceback object at 0x0000022DE36B8A00>)
2023-07-06 19:47:26,101 ERROR handle_logs type: Exit -> traceback:"    (<frame at 0x000002292EE24C20, file 'C:\\Users\\BURI\\Desktop\\add_all_extra\\python\\BuriScript - A Code Editor\\TypeRacer\\buriracer_window.py', line 377, code <lambda>>, 40, 377, <traceback object at 0x000002292EFF1300>)
2023-07-06 20:21:04,682 ERROR handle_logs type: name 'CustomWidget' is not defined -> traceback:"    (<frame at 0x00000207A03B5940, file 'C:\\Users\\BURI\\Desktop\\add_all_extra\\python\\BuriScript - A Code Editor\\TypeRacer\\buriracer_window.py', line 347, code <lambda>>, 40, 347, <traceback object at 0x000002079B372380>)
2023-07-06 20:23:21,182 ERROR handle_logs type: wrapped C/C++ object of type QLabel has been deleted -> traceback:"    (<frame at 0x000002032DF797B0, file 'C:\\Users\\BURI\\Desktop\\add_all_extra\\python\\BuriScript - A Code Editor\\TypeRacer\\buriracer_window.py', line 223, code calculate_live_wpm>, 1240, 222, <traceback object at 0x000002030BA061C0>)
2023-07-06 20:23:21,200 ERROR handle_logs type: wrapped C/C++ object of type QLabel has been deleted -> traceback:"    (<frame at 0x000002032DF8E5C0, file 'C:\\Users\\BURI\\Desktop\\add_all_extra\\python\\BuriScript - A Code Editor\\TypeRacer\\buriracer_window.py', line 223, code calculate_live_wpm>, 1240, 222, <traceback object at 0x000002032D939980>)
2023-07-08 15:41:53,683 ERROR handle_logs TypeError, (TypeError('PyQt5.Qsci.QsciLexerCustom represents a C++ abstract class and cannot be instantiated'), ('type', <traceback object at 0x000001EFB2BA6F80>, <traceback object at 0x000001EFB2BA7600>, 234, 138, <frame at 0x000001EFB85B06D0, file 'C:\\Users\\BURI\\Desktop\\add_all_extra\\python\\BuriScript - A Code Editor\\BuriScriptTabView.py', line 236, code add_new_tab>)), {}
2023-07-11 21:41:05,418 ERROR handle_logs type: 'CustomSlider' object has no attribute 'changeValue' -> traceback:"    (<frame at 0x0000029244C7DDA0, file 'C:\\Users\\BURI\\Desktop\\add_all_extra\\python\\BuriScript - A Code Editor\\MySQLScintilla\\MySQLScintillaMain.py', line 179, code <lambda>>, 40, 179, <traceback object at 0x0000029244E84C80>)
2023-07-11 21:41:25,195 ERROR handle_logs type: CustomSlider.value_changed() missing 1 required positional argument: 'value' -> traceback:"    (<frame at 0x0000020699B62CA0, file 'C:\\Users\\BURI\\Desktop\\add_all_extra\\python\\BuriScript - A Code Editor\\MySQLScintilla\\MySQLScintillaMain.py', line 179, code <lambda>>, 40, 179, <traceback object at 0x0000020699D39200>)
2023-07-11 21:41:37,269 ERROR handle_logs type: 'PopUpWindow' object has no attribute '_table_widget' -> traceback:"    (<frame at 0x000001CCBDE9D0C0, file 'C:\\Users\\BURI\\Desktop\\add_all_extra\\python\\BuriScript - A Code Editor\\MySQLScintilla\\MySQLScintillaMain.py', line 104, code value_changed>, 14, 104, None)
2023-07-12 07:00:10,776 ERROR handle_logs type: [WinError 267] The directory name is invalid: 'C:/Users/BURI/Desktop/add_all_extra/python/BuriScript/AI.txt' -> traceback:"    (<frame at 0x000002558CCBF040, file 'C:\\Users\\BURI\\Desktop\\add_all_extra\\python\\BuriScript - A Code Editor\\main.py', line 1020, code run_python_file>, 1148, 1020, <traceback object at 0x000002558E96A1C0>)
2023-07-12 07:03:17,126 ERROR handle_logs type: [WinError 267] The directory name is invalid: 'C:/Users/BURI/Desktop/add_all_extra/python/BuriScript/AI.txt' -> traceback:"    (<frame at 0x000001A4C14628C0, file 'C:\\Users\\BURI\\Desktop\\add_all_extra\\python\\BuriScript - A Code Editor\\main.py', line 1019, code run_python_file>, 1148, 1019, <traceback object at 0x000001A4C2BB6040>)
2023-07-12 07:03:23,899 ERROR handle_logs type: [WinError 267] The directory name is invalid: 'C:/Users/BURI/Desktop/add_all_extra/python/BuriScript/AI.txt' -> traceback:"    (<frame at 0x00000218A2CB28C0, file 'C:\\Users\\BURI\\Desktop\\add_all_extra\\python\\BuriScript - A Code Editor\\main.py', line 1019, code run_python_file>, 1148, 1019, <traceback object at 0x00000218A44055C0>)
2023-07-12 07:03:39,860 ERROR handle_logs type: [WinError 267] The directory name is invalid: 'C:/Users/BURI/Desktop/add_all_extra/python/BuriScript/AI.txt' -> traceback:"    (<frame at 0x00000212FB1A28C0, file 'C:\\Users\\BURI\\Desktop\\add_all_extra\\python\\BuriScript - A Code Editor\\main.py', line 1019, code run_python_file>, 1148, 1019, <traceback object at 0x00000212FC8F4E40>)
2023-07-12 07:04:03,597 ERROR handle_logs type: [WinError 267] The directory name is invalid: 'C:/Users/BURI/Desktop/add_all_extra/python/BuriScript/AI.txt' -> traceback:"    (<frame at 0x000001C5E92828C0, file 'C:\\Users\\BURI\\Desktop\\add_all_extra\\python\\BuriScript - A Code Editor\\main.py', line 1020, code run_python_file>, 1148, 1020, <traceback object at 0x000001C5EA9D4BC0>)
2023-07-12 07:04:17,225 ERROR handle_logs type: [WinError 267] The directory name is invalid: 'C:/Users/BURI/Desktop/add_all_extra/python/BuriScript/AI.txt' -> traceback:"    (<frame at 0x0000027BE8FC28C0, file 'C:\\Users\\BURI\\Desktop\\add_all_extra\\python\\BuriScript - A Code Editor\\main.py', line 1020, code run_python_file>, 1148, 1020, <traceback object at 0x0000027BEA715440>)
2023-07-12 07:05:04,359 ERROR handle_logs type: [WinError 267] The directory name is invalid: 'C:/Users/BURI/Desktop/add_all_extra/python/BuriScript/AI.txt' -> traceback:"    (<frame at 0x000001C347C528C0, file 'C:\\Users\\BURI\\Desktop\\add_all_extra\\python\\BuriScript - A Code Editor\\main.py', line 1020, code run_python_file>, 1148, 1020, <traceback object at 0x000001C3493A5440>)
2023-07-12 07:05:31,454 ERROR handle_logs type: [WinError 267] The directory name is invalid: 'C:/Users/BURI/Desktop/add_all_extra/python/BuriScript/AI.txt' -> traceback:"    (<frame at 0x0000025A708B28C0, file 'C:\\Users\\BURI\\Desktop\\add_all_extra\\python\\BuriScript - A Code Editor\\main.py', line 1021, code run_python_file>, 1148, 1021, <traceback object at 0x0000025A72005800>)
2023-07-12 07:06:02,890 ERROR handle_logs type: [WinError 267] The directory name is invalid: 'C:/Users/BURI/Desktop/add_all_extra/python/BuriScript/AI.txt' -> traceback:"    (<frame at 0x000002D5AA7728C0, file 'C:\\Users\\BURI\\Desktop\\add_all_extra\\python\\BuriScript - A Code Editor\\main.py', line 1020, code run_python_file>, 1148, 1020, <traceback object at 0x000002D5ABEC5040>)
2023-07-12 07:10:01,133 ERROR handle_logs NotADirectoryError, (NotADirectoryError(20, 'The directory name is invalid'), ('type', <traceback object at 0x0000023278711740>, None, 1002, 78, <frame at 0x0000023277046840, file 'C:\\Users\\BURI\\Desktop\\add_all_extra\\python\\BuriScript - A Code Editor\\main.py', line 1004, code run_function>)), {}
2023-07-27 06:10:33,705 ERROR handle_logs type:  -> traceback:"    (<frame at 0x000001E6EEE6C940, file 'C:\\Users\\BURI\\Desktop\\add_all_extra\\python\\BuriScript - A Code Editor\\PythonInterpreter.py', line 90, code on_readyReadStandardOutput>, 30, 90, None)
